### ISSUE TITLE
Add a tracking header

### ISSUE THREAD

**Issue by petrsvihlik** [Domitnator/kentico-kontent-nuxt-module#10]
There's a tracking header called `X-KC-SOURCE` that you can add to your plugin. We'll be then able to measure the adoption of your plugin and send you statistics of API calls made through the plugin.

You can set the header via the Kentico Kontent Delivery SDK.

v5 JS SDK approach: https://github.com/Kentico/gatsby-source-kentico-cloud/commit/e3612ae18f6bfedeb1a51e8d754000b927151e28

v6 JS SDK: https://github.com/Kentico/gatsby-source-kentico-cloud/blob/js-sdk-ugrade-v6/src/gatsby-node.js#L96 or https://github.com/Kentico/gatsby-source-kentico-cloud/blob/master/src/gatsby-node.js#L96

**Comment by Domitnator** [comment]
commit e1294a9603520bc2977b4192a7fa127ab5b90c29 fixed this issue!

**Comment by Domitnator** [comment]
Has been fixed in [release V3](https://www.npmjs.com/package/kentico-kontent-nuxt-module)
