### ISSUE TITLE
Rebranding to Kentico Kontent

### ISSUE THREAD

**Issue by petrsvihlik** [Domitnator/kentico-kontent-nuxt-module#11]
Hi @Domitnator !
We've just renamed Kentico Cloud to [Kentico Kontent](https://kontent.ai/blog/moving-to-caas-with-kentico-kontent). We are in the process of renaming all SDKs and Sample apps. Please consider renaming your plugin (code: namespaces, classes; repo, wiki, GH topics, etc.) to Kentico Kontent.

Thanks!

**Comment by Domitnator** [comment]
@petrsvihlik Thanks for reaching out. I will rename my repo accordingly! Probably next week 👍

**Comment by petrsvihlik** [comment]
Guidelines: https://gitter.im/Kentico/Kontent?at=5d8b643d692d464f7969c6d9

**Comment by Domitnator** [comment]
@petrsvihlik The change is done but i made a versioning mistake so i needed to unpublish the npm package. Now i need to wait 24 hours before i can republish the new version.

**Comment by petrsvihlik** [comment]
lovely!

**Comment by Domitnator** [comment]
Version 3 has been released [on npm](https://www.npmjs.com/package/kentico-kontent-nuxt-module)
