### ISSUE TITLE
DeliveryClient requests fail when secure mode is enabled

### ISSUE THREAD

**Issue by davidlaughlintl** [Domitnator/kentico-kontent-nuxt-module#45]
Hi! We really like this module; thanks for creating it! 

Found a problem when we switched our nuxt.config.js usePreviewMode to false, set enableSecureMode to true, and switched Kentico's secure access option on for the production delivery api. Our requests to the Delivery Api were failing with the usual message when the Authorization header isn't correct.

In module.js, there's a couple properties that don't match the [current Kentico js SDK docs](https://docs.kontent.ai/tutorials/develop-apps/build-strong-foundation/restrict-public-access?tech=javascript#a-retrieve-content-securely):
secure**d**ApiKey => secureApiKey
**enable**SecureMode => useSecureMode
useSecureMode is a property of the globalQueryConfig object in the Kentico docs.

Making those changes in our local module.js and making matching changes in nuxt.config.js resolved the problem for us.

Would you like me to open a PR with these changes (and the nuxt.config.js section of the Readme docs)?

Thanks again for your work on this!
David

**Comment by Domitnator** [comment]
Hi David,

Thanks for opening this issue! I will fix this issue asap (probably on wednesday)!

Kind Regards,

Alfred
